### PR TITLE
Bootstrap 5 - Event Fixes and Contact Form Captcha

### LINKED ISSUE #163: For long search forms, only show first X number of fields, and put the rest in an accordion
The search forms are really long (1 full page scroll on l/xl) and we should hide what isn't used as much.

### PR DESCRIPTION
**Pull request by mickzijdel**
- Add captcha to contact form
- Move the map to the top of the accessibility page
- Add proposal archive link to the admin side bar & move Festivals and Seasons
- Fix ordering of events in the public front end non-archive pages and hide the search form.
- Link to all events on the venue admin page rather than just shows.
- Maps:
  - Replace existing maps (venue show and accessibility/find us) with openstreetmaps using leaflet
  - Add map to admin venue show page
  - Add map with all venues to the admin site
- Set navigation items with a helper instead of the controller so it no longer errors when redirecting between layouts.
- Collapsible search forms. Fixes #163 
- Fix adding user to role form.

### CODE REVIEW

File: app/assets/javascripts/application.js [hunk 1]
```diff
@@ -10,7 +10,7 @@
 // WARNING: THE FIRST BLANK LINE MARKS THE END OF WHAT'S TO BE PROCESSED, ANY BLANK LINE SHOULD
 // GO AFTER THE REQUIRES BELOW.
 //
-
 //= require raphael-min
 //= require dracula_graffle
-//= require dracula_graph
\ No newline at end of file
+//= require dracula_graph
+//=require leaflet
```
Comment (AlexanderMohan) [inline app/assets/javascripts/application.js:16]: these should end with a newline

File: app/helpers/navigation_helper.rb [hunk 2]
```diff
@@ -0,0 +1,100 @@
+module NavigationHelper
```
Comment (AlexanderMohan) [inline app/helpers/navigation_helper.rb:1]: this works, but what's the purpose of this reorg?

File: app/models/role.rb [hunk 3]
```diff
@@ -18,7 +18,7 @@
 class Role < ApplicationRecord
   # The roles that are referenced directly in the code.
   # Changing the name would break the website, so this list is used to prevent name changes for these roles.
-  HARDCODED_NAMES = ['Admin', 'Member', 'Committee', 'DM Trained', 'Business Manager'].freeze
```
Comment (AlexanderMohan) [inline app/models/role.rb:21]: while you're doing this, can you add alcohol trained?

Comment (AlexanderMohan) [reply app/models/role.rb:21]: call it bar trained actually

**Review by AlexanderMohan — CHANGES_REQUESTED** [review]
interested in some decisions, main request for change is to add a Bar Trained role.

File: app/helpers/navigation_helper.rb (hunk 2 above)
Comment (mickzijdel) [reply app/helpers/navigation_helper.rb:1]: The previous version would error when a user without :access_to_backend permission would try to access the admin side. This was because the admin_controller had overridden the method where the navbar items get generated, and thus the application navbar did not get the fields it expected. This way it doesn't matter which controller points someone to a layout anymore, which is more robust

File: app/models/role.rb (hunk 3 above)
Comment (mickzijdel) [reply app/models/role.rb:21]: Done

File: app/assets/javascripts/application.js (hunk 1 above)
Comment (mickzijdel) [reply app/assets/javascripts/application.js]: Done

**Review by AlexanderMohan — APPROVED** [review]
